### ISSUE TITLE
急需一个清爽点的主题

### ISSUE THREAD

**Issue by lujun9972** [emacs-china/EGO#100]
现在这个默认的主题颜色太重了…

**Comment by lujun9972** [comment]
他兼容org-webpage的主题吗？

**Comment by kuangdash** [comment]
目前可以使用 org-webpage 的主题，只是评论系统要从两个改成一个，然后是右上的目录不会自动切换了。org-webpage 和 EGO 的区别主要是 upload 的部分。

**Comment by lujun9972** [comment]
右上角的目录切换是由哪部分控制的？

**Comment by kuangdash** [comment]
一个借助 jquery 的 js 文件，在theme 的 js 文件夹下，main.js，需要在 footer.mustache 里面挂上这个 js 的文件路径
