### ISSUE TITLE
有时候生成的主页中会缺少文章

### ISSUE THREAD

**Issue by lujun9972** [emacs-china/EGO#101]
比如对比https://lujun9972.github.io/years/
和https://lujun9972.github.io/
会发现前面有 [使用cryptmount创建加密镜像保存机密文件](https://lujun9972.github.io/blog/2018/02/08/%E4%BD%BF%E7%94%A8cryptmount%E5%88%9B%E5%BB%BA%E5%8A%A0%E5%AF%86%E9%95%9C%E5%83%8F%E4%BF%9D%E5%AD%98%E6%9C%BA%E5%AF%86%E6%96%87%E4%BB%B6/)

而后面的主页中没这篇文章

@kuangdash

**Comment by kuangdash** [comment]
不是有吗？是前期没有，后面自己加上的？

**Comment by kuangdash** [comment]
EGO 有一个更新必须经过测试更新的要求，而且 git checkin 要选对（就是 publication 时候的 “~head” 那里），虽然默认情况下不会出问题，但是不注意的话确实会出现情况

**Comment by lujun9972** [comment]
为啥要强制测试呢…

**Comment by kuangdash** [comment]
并不是强制测试，而是只有测试后的才能被上传。不过这里的交互设计是有改进余地，但我不想在这个版本上打磨了…
