### ISSUE TITLE
ego/new-repository同时创建master与source分支

### ISSUE THREAD

**Issue by lujun9972** [emacs-china/EGO#56]
ego/new-repository同时创建master与source分支

同时，about.org与index.org,README应该放到source分支中

函数的最后，把当前分支切换到source分支

**Comment by kuangdash** [comment]
我把 ego/new-repository 的参数 source-branch 和 html-branch 顺序写反了，低级失误……

**Comment by kuangdash** [comment]
先解决些简单的 https://github.com/emacs-china/EGO/pull/57/files
