### ISSUE TITLE
ego安装在24.5版本的emacs出错

### ISSUE THREAD

**Issue by hyloong** [emacs-china/EGO#64]
坏境 mac
安装方法 brew install emacs
版本：GNU Emacs 24.5.1
安装ego后，启动会缺少seq.el和cl－generic.el,我简单添加这两个文件，不能解决问题。
看看没有好的方法，帮我解决一下。

**Comment by lujun9972** [comment]
(require 'seq)
(require 'eieio)?

**Comment by kuangdash** [comment]
先要确认你添加的文件是不是在 load-path 里（用 C-h v 查阅这个变量）

seq 的问题我听几个人提到过，很抱歉，这个问题是我用 emacs-25 branch 的 emacs 开发导致的……

目前是先将 ego 提交到 melpa（可能就解决 seq 问题了）？还是先完善 ego-manager.el #62  ？还是先写出 ego-map.el ？还是先完善测试流程 #63 ？我还拿不定主意。

……总之，新年快乐

**Comment by lujun9972** [comment]
seq的问题好解决，可以用cl-lib代替

我觉得先放melpa吧，其他的还有待斟酌

**Comment by hyloong** [comment]
@kuangdash 之前试过了，是不行的。不过等你们先把ego弄上mepla吧，后续问题遇到了我会再问，新年快乐

**Comment by kuangdash** [comment]
#66 用 dash.el 本身的功能替代 seq 了，emacs 24.5 上测试没问题。  目前这个版本的 EGO 先凑合着…
