### ISSUE TITLE
More .org files that are not treated as blog posts.

### ISSUE THREAD

**Issue by tmalsburg** [emacs-china/EGO#81]
If I understand correctly, `index.org` and `about.org` are the only `.org` files that are not treated as blog posts.  Any other `.org` file will be processed as a blog post, that means, it will be listed in the index and the template `post.mustache` will be used to render it.

Is it possible to add new non-blog-post `.org` files?

What I want to do is to add more pages like `about.org` on which I provide additional information, for example, my publications.

Thank you!

**Comment by tmalsburg** [comment]
I think the solution may be to use categories but it's not clear to me how that works and the startpage says that it's not recommended to use categories.

**Comment by tmalsburg** [comment]
I think I found a solution. When creating a new post (`ego-new-post`) just enter "about" as the category.  The `.org` file will then be created in the directory `/about/` which is fine in my case.  The HTML file will be in whatever location is specified in the `#+URI` header.

**Comment by kuangdash** [comment]
First, I have to admit that the structure of EGO doesn't get well now. The categories configure is a mass.

Second, category is only a special case of tags. You can use tags to replace it.

**Comment by tmalsburg** [comment]
Thank you, this is very helpful.
