### ISSUE TITLE
Symbol's function definition is void: string-trim (when publishing)

### ISSUE THREAD

**Issue by zhcosin** [emacs-china/EGO#86]
The error "Symbol's function definition is void: string-trim" has been occur when I execute ego-test-current-page or ego-do-publication. 
emacs-24.5-bin-i686-mingw32 on windows 7.
ego has been installed by packages as ego-20160822.849

**Comment by kuangdash** [comment]
`string-trim' is located in `subr-x.el.gz' which emacs provides by default.

Use `(require 'subr-x)' then it can be done.

**Comment by zhcosin** [comment]
Thanks, this solution is OK.

**Comment by lujun9972** [comment]
Which means should add the '(require 'subr-x)' into the source file.
