### ISSUE TITLE
apply: Wrong type argument: listp, #("lujun9972" 0 9 (:parent (#0)))

### ISSUE THREAD

**Issue by lujun9972** [emacs-china/EGO#88]
I'm trying to publish the "https://github.com/lujun9972/emacs-document", but I get the error:

> EGO: verify configuration
> EGO: Git branch operation and get changed files
> EGO: Create necessary directory and prepare theme!
> EGO: Pre-publish all files needed to be publish, waiting...
> (:title emacs-calc :date 2016-07-06 :mod-date 2016-07-06 :description No Description :thumb nil :authors (lujun9972) :category calc :uri /blog/2016/07/06/emacs-calc/ :pub-dir /home/lujun9972/webRoot/emacs-document.github.io/blog/2016/07/06/emacs-calc/)
> Read post.mustache from file
> apply: Wrong type argument: listp, #("lujun9972" 0 9 (:parent (#0)))
> 

My configuration is 
```emacs-lisp
(use-package ego
      :config
      (ego-add-to-alist 'ego-project-config-alist
               `(("emacs-document" ; 站点工程的名字
                 :repository-directory "~/github/emacs-document" ; 站点的本地目录
                 :site-domain "http://lujun9972.github.io/emacs-document" ; 站点的网址
                 :site-main-title "EMACS-DOCUMENT" ; 站点的标题
                 :site-sub-title "=============>集思广益" ; 站点的副标题
                 :repository-org-branch "master"
                 :repository-html-branch "gh-pages"
                 :theme (default) ; 使用的主题
                 :summary (("years" :year :updates 10) ("authors" :authors) ("tags" :tags)) ; 导航栏的设置，有 category 和 summary 两种
                 :source-browse-url ("Github" "https://github.com/lujun9972/emacs-document") ; 你的工程源代码所在的位置
                 :personal-disqus-shortname "emacs-document" ; 使用 disqus 评论功能的话，它的短名称
                 :personal-duoshuo-shortname "emacs-document" ; 使用 多说 评论功能的话，它的短名称
                 ;; :confound-email nil ; 是否保护邮件名称呢？t 是保护，nil 是不保护，默认是保护
                 :ignore-file-name-regexp "README.org" ; 有些不想发布成 html 的 org 文件（但是又想被导入 git 进行管理），可以用这种正则表达的方式排除
                 :web-server-docroot "~/webRoot/emacs-document.github.io" ; 本地测试的目录
                 :web-server-port 5432); 本地测试的端口

                 ;; 你可以在此添加更多的站点设置
               )))
```

**Comment by lujun9972** [comment]
Org-version:8.3.6
Emacs-vesion:26.0.50.1
System:Ubuntu 16.04

**Comment by kuangdash** [comment]
It seems to be the problem of mustache.el and  `org-export-as`,

`M-x toggle-debug-on-error`, May I solve the problem...
