### ISSUE TITLE
fontnote bug with default theme

### ISSUE THREAD

**Issue by CodeFalling** [emacs-china/EGO#9]
当鼠标移向第十个角标时，浏览器报错
```
Uncaught TypeError: Cannot read property 'parentNode' of null
```
定位到`main.js`第73行，`var nodeNew = docNode.parentNode.parentNode.cloneNode(true);`

**Comment by kuangdash** [comment]
Sorry, It‘s my fault that the map logic is wrong.

Now, It has been fixed, thank you~

**Comment by kuangdash** [comment]
MENTION: set the "option: H:4" in org-file will resolve the problem of table-of-content in http://codefalling.com/blog/2015/09/05/write-your-own-mini-games-with-javascript

**Comment by CodeFalling** [comment]
Thx~
