### ISSUE TITLE
Does ego support links between posts?

### ISSUE THREAD

**Issue by tsdh** [emacs-china/EGO#93]
I currently use org-page. The single feature which it doesn't support is linking between org files. That is, you can link them but then the links in the generated html files are wrong. Does ego transform links correctly when exporting?

**Comment by kuangdash** [comment]
Partially supports it. After `(require 'ego)`, use  C-c C-l `ego-links:` then it can be done.

**Comment by tsdh** [comment]
Ok, thanks.
