### ISSUE TITLE
为什么分类变成了".."

### ISSUE THREAD

**Issue by lujun9972** [emacs-china/EGO#96]
https://github.com/lujun9972/lujun9972.github.com/blob/source/Emacs%E4%B9%8B%E6%80%92/Emacs%E4%BD%9C%E4%B8%BA%E5%9B%BE%E7%89%87%E6%B5%8F%E8%A7%88%E5%99%A8.org

我的这篇文章,明明是放在"Emacs之怒"文件夹下的,但是不知道为什么导出成HTML时,它的分类变成了".."

**Comment by Liu233w** [comment]
是不是因为没有写 `URI` 选项？

**Comment by kuangdash** [comment]
EGO 的 category 对两层目录之下的文件没有很好的支持，这个在其相关代码里看的到…

使用 tags 替代 categories 是可以的。不过要把一个特定 tag 提上导航栏，就要求比目前的 EGO 更灵活的主题映射方式了。

**Comment by lujun9972** [comment]
?? 在我看来tag和category完全是两个不同的东西，不存在谁替代谁的问题呀。

这个算是个BUG吧，能不能修改

**Comment by kuangdash** [comment]
还记得 #88 吗？我那天在 QQ 里帮你排查了，结果是 org-export-as ，也就是 org 版本太新（也可能是其他设置）造成的。

这次在我重现场景前要问几个问题：
1、该目录下其他文章是否是同样的情况？
2、如果将目录名改为全英文是否还会出现同样的情况？
3、跟踪 ego--get-file-category 函数返回的结果是？

我没有从源码里找到造成该现象的原因。

**Comment by lujun9972** [comment]
直到原因了,我这个文件是其他目录下文件的链接.

而我又在其他目录下打开了这个文件. 那么导出是expand-filename会expand成其他目录下的路径.再计算repo目录的相对路径时结果就会是 "../xxx/yyy/" 这样的东西,然后split再car的结果就是..了

**Comment by kuangdash** [comment]
这种私人设置很难排查…找到原因就好，那我先关闭这个 issue 了
